name: Deploy MusicFun Apps to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install deps for tanstack-query
        working-directory: apps/musicfun-tanstack-query
        run: pnpm install --no-frozen-lockfile

      - name: Install deps for rtk-query
        working-directory: apps/musicfun-rtk-query
        run: pnpm install --no-frozen-lockfile

      - name: Build tanstack-query
        working-directory: apps/musicfun-tanstack-query
        run: pnpm build

      - name: Build rtk-query
        working-directory: apps/musicfun-rtk-query
        run: pnpm build

      - uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: SPA fallback for tanstack-query
        working-directory: apps/musicfun-tanstack-query/dist
        run: cp index.html 404.html

      - name: SPA fallback for rtk-query
        working-directory: apps/musicfun-rtk-query/dist
        run: cp index.html 404.html

      - name: Prepare deployment folder
        run: |
          mkdir -p dist/tanstackquery
          mkdir -p dist/rtkquery
          cp -r apps/musicfun-tanstack-query/dist/* dist/tanstackquery/
          cp -r apps/musicfun-rtk-query/dist/* dist/rtkquery/
          touch dist/.nojekyll

      - name: Copy root index.html
        run: cp public/index.html dist/index.html

      - name: Create 404.html for SPA fallback
        run: |
          cat > dist/404.html << 'EOF'
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Redirecting...</title>
              <script>
                // SPA redirect for GitHub Pages
                (function() {
                  var path = window.location.pathname;
                  var search = window.location.search;
                  var hash = window.location.hash;

                  // Determine which app the path belongs to
                  if (path.startsWith('/tanstackquery/') || path === '/tanstackquery') {
                    var fullPath = path + search + hash;
                    window.location.replace('/tanstackquery/?spa_redirect=' + encodeURIComponent(fullPath));
                  } else if (path.startsWith('/rtkquery/') || path === '/rtkquery') {
                    var fullPath = path + search + hash;
                    window.location.replace('/rtkquery/?spa_redirect=' + encodeURIComponent(fullPath));
                  } else {
                    // Unknown path, redirect to home
                    window.location.replace('/');
                  }
                })();
              </script>
            </head>
            <body></body>
          </html>
          EOF

      - name: Add CNAME
        run: echo 'app.musicfun.dev' > dist/CNAME

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - id: deployment
        uses: actions/deploy-pages@v4