name: Deploy musicfun-rtk-query to GitHub Pages

on:
  push:
    branches: [deploy]            # пушишь в ветку deploy — сайт обновляется
  workflow_dispatch:              # можно запускать руками из Actions

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # ставим pnpm (версию возьмет из package.json->packageManager, если есть)
      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      # Устанавливаем зависимости БЕЗ frozen-lockfile
      - name: Install deps
        working-directory: apps/tanstack-query
        run: pnpm install --no-frozen-lockfile

      # Сборка Vite (должна вывести в ./dist)
      - name: Build
        working-directory: apps/tanstack-query
        run: pnpm build

      # Паблиш на GitHub Pages
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: apps/tanstack-query/dist
      - uses: actions/deploy-pages@v4
